import { getRedis } from "./redis";
import type { Timeframe } from "@/types";

// TTL per timeframe — shorter timeframes need fresher signals
const SIGNAL_TTL: Record<Timeframe, number> = {
  "5M":  3 * 60,    // 3 min
  "15M": 5 * 60,    // 5 min
  "1H":  10 * 60,   // 10 min
  "4H":  20 * 60,   // 20 min
  "1D":  60 * 60,   // 1 hour
};

const COMMENTARY_TTL = 30 * 60;  // 30 min — re-generated by cron
const NEWS_TTL = 60 * 60;        // 1 hour

// Round price to nearest $1 to group near-identical market conditions
function priceKey(price: number): string {
  return String(Math.round(price));
}

export const CacheKey = {
  signal: (timeframe: Timeframe, price: number) =>
    `signal:${timeframe}:${priceKey(price)}`,
  commentary: () => "commentary:latest",
  newsHeadlines: () => "news:headlines",
  newsAnalyzed: (hash: string) => `news:analyzed:${hash}`,
};

async function get<T>(key: string): Promise<T | null> {
  try {
    const redis = getRedis();
    const raw = await redis.get(key);
    if (!raw) return null;
    return JSON.parse(raw) as T;
  } catch {
    return null;
  }
}

async function set(key: string, value: unknown, ttl: number): Promise<void> {
  try {
    const redis = getRedis();
    await redis.set(key, JSON.stringify(value), "EX", ttl);
  } catch {
    // Silent fail — cache is non-critical
  }
}

async function del(key: string): Promise<void> {
  try {
    await getRedis().del(key);
  } catch {}
}

// ── High-level cache helpers ──────────────────────────────────────────────

export async function getCachedSignal<T>(timeframe: Timeframe, price: number): Promise<T | null> {
  return get<T>(CacheKey.signal(timeframe, price));
}

export async function setCachedSignal<T>(timeframe: Timeframe, price: number, value: T): Promise<void> {
  return set(CacheKey.signal(timeframe, price), value, SIGNAL_TTL[timeframe]);
}

export async function getCachedCommentary<T>(): Promise<T | null> {
  return get<T>(CacheKey.commentary());
}

export async function setCachedCommentary<T>(value: T): Promise<void> {
  return set(CacheKey.commentary(), value, COMMENTARY_TTL);
}

export async function invalidateCommentary(): Promise<void> {
  return del(CacheKey.commentary());
}

export async function getCachedNews<T>(hash: string): Promise<T | null> {
  return get<T>(CacheKey.newsAnalyzed(hash));
}

export async function setCachedNews<T>(hash: string, value: T): Promise<void> {
  return set(CacheKey.newsAnalyzed(hash), value, NEWS_TTL);
}

export async function getCachedHeadlines<T>(): Promise<T | null> {
  return get<T>(CacheKey.newsHeadlines());
}

export async function setCachedHeadlines<T>(value: T): Promise<void> {
  return set(CacheKey.newsHeadlines(), value, NEWS_TTL);
}

// Generic cache-aside helper
export async function withCache<T>(
  key: string,
  ttl: number,
  fn: () => Promise<T>
): Promise<T> {
  const cached = await get<T>(key);
  if (cached !== null) return cached;
  const fresh = await fn();
  await set(key, fresh, ttl);
  return fresh;
}
